services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - REDIS_ADDR=${REDIS_ADDR}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USERNAME=${SMTP_USERNAME}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        volumes:
            - ./templates:/app/templates
            - ./attachments:/app/attachments
